# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_proto_test import connection_pb2 as connection__pb2


class ConnectionServiceStub(object):
    """Client stub for the demo connection service."""

    def __init__(self, channel):
        self.Ping = channel.unary_unary(
            '/demo.ConnectionService/Ping',
            request_serializer=connection__pb2.PingRequest.SerializeToString,
            response_deserializer=connection__pb2.PingReply.FromString,
        )
        self.GetMockTask = channel.unary_unary(
            '/demo.ConnectionService/GetMockTask',
            request_serializer=connection__pb2.MockTaskRequest.SerializeToString,
            response_deserializer=connection__pb2.MockTaskReply.FromString,
        )


class ConnectionServiceServicer(object):
    """Base servicer class for the demo connection service."""

    def Ping(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMockTask(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Ping': grpc.unary_unary_rpc_method_handler(
            servicer.Ping,
            request_deserializer=connection__pb2.PingRequest.FromString,
            response_serializer=connection__pb2.PingReply.SerializeToString,
        ),
        'GetMockTask': grpc.unary_unary_rpc_method_handler(
            servicer.GetMockTask,
            request_deserializer=connection__pb2.MockTaskRequest.FromString,
            response_serializer=connection__pb2.MockTaskReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'demo.ConnectionService', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


class ConnectionService(object):
    """Experimental helper for calling the service without a stub."""

    @staticmethod
    def Ping(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.ConnectionService/Ping',
            connection__pb2.PingRequest.SerializeToString,
            connection__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetMockTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.ConnectionService/GetMockTask',
            connection__pb2.MockTaskRequest.SerializeToString,
            connection__pb2.MockTaskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
