# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x12\x04\x64\x65mo\"6\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x16\n\x0e\x63lient_time_ms\x18\x02 \x01(\x03\"M\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x17\n\x0fserver_hostname\x18\x02 \x01(\t\x12\x16\n\x0eserver_time_ms\x18\x03 \x01(\x03\"&\n\x0fMockTaskRequest\x12\x13\n\x0bworker_name\x18\x01 \x01(\t\"\xab\x01\n\rMockTaskReply\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x02 \x01(\t\x12\x13\n\x0bshard_index\x18\x03 \x01(\x05\x12\x14\n\x0ctotal_shards\x18\x04 \x01(\x05\x12\x0e\n\x06\x65pochs\x18\x05 \x01(\x05\x12\x12\n\nbatch_size\x18\x06 \x01(\x05\x12\x15\n\rlearning_rate\x18\x07 \x01(\x01\x12\r\n\x05notes\x18\x08 \x01(\t2z\n\x11\x43onnectionService\x12*\n\x04Ping\x12\x11.demo.PingRequest\x1a\x0f.demo.PingReply\x12\x39\n\x0bGetMockTask\x12\x15.demo.MockTaskRequest\x1a\x13.demo.MockTaskReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _PINGREQUEST._serialized_start = 26
    _PINGREQUEST._serialized_end = 80
    _PINGREPLY._serialized_start = 82
    _PINGREPLY._serialized_end = 159
    _MOCKTASKREQUEST._serialized_start = 161
    _MOCKTASKREQUEST._serialized_end = 199
    _MOCKTASKREPLY._serialized_start = 202
    _MOCKTASKREPLY._serialized_end = 373
    _CONNECTIONSERVICE._serialized_start = 375
    _CONNECTIONSERVICE._serialized_end = 497
# @@protoc_insertion_point(module_scope)
